[package]
name = "wasm_newtype_proc_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
crate-type = ["proc-macro"]

[dependencies]
quote = "1.0.40"
syn = "2.0.100"
wasm_newtype = { path = "../wasm_newtype" }
