[package]
name = "wasm_newtype"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
validator = { version = "0.20.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.100", features = ["serde"] }
